<?php

$regions = [
    "NCR" => "National Capital Region",
    "CAR" => "Cordillera Administrative Region",
    "REGION I" => "Ilocos Region",
    "REGION II" => "Cagayan Valley",
    "REGION III" => "Central Luzon",
    "REGION IV-A" => "CALABARZON",
    "REGION IV-B" => "MIMAROPA",
    "REGION V" => "Bicol Region",
    "REGION VI" => "Western Visayas",
    "NIR" => "Negros Island Region",
    "REGION VII" => "Central Visayas",
    "REGION VIII" => "Eastern Visayas",
    "REGION IX" => "Zamboanga Peninsula",
    "REGION X" => "Northern Mindanao",
    "REGION XI" => "Davao Region",
    "REGION XII" => "SOCCSKSARGEN",
    "REGION XIII" => "Caraga",
    "BARMM" => "Bangsamoro Autonomous Region in Muslim Mindanao",
];

$provinces_NCR = [
    "City of Caloocan",
    "City of Las Piñas",
    "City of Makati",
    "City of Malabon ",
    "City of Mandaluyong",
    "City of Manila",
    "Tondo I/II",
    "Binondo",
    "Quiapo",
    "San Nicolas",
    "Santa Cruz",
    "Sampaloc",
    "San Miguel",
    "Ermita",
    "Intramuros",
    "Malate",
    "Paco",
    "Pandacan",
    "Port Area",
    "Santa Ana",
    "City of Marikina",
    "City of Muntinlupa",
    "City of Navotas",
    "City of Parañaque",
    "Pasay City",
    "City of Pasig",
    "Quezon City",
    "City of San Juan",
    "City of Taguig",
    "City of Valenzuela",
    "Pateros",
];
